In [1]:
#this is a comment
num=100

In [2]:
print(num)

100


In [3]:
type(num)

int

In [4]:
num3=10.5

In [6]:
type(num3)

float

In [7]:
str="Amrita"

In [8]:
type(str)

str

In [10]:
str1="Amrita Rout"

In [11]:
print(str1)

Amrita Rout


In [20]:
Color_list=['red','blue','orange','yellow']

In [36]:
Number_list=[1,2,3,4,'red',10.3]

In [22]:
print(Color_list)

['red', 'blue', 'orange', 'yellow']


In [34]:
Color_list[0]

'red'

In [30]:
str2='Welcome to python'
str3='hellow 1st python session'

In [33]:
print(str1)
print(str1 +' '+ str2)

Amrita Rout
Amrita Rout Welcome to python


In [37]:
Number_list[4]

'red'

In [42]:
a=50

In [43]:
a>10

True

In [44]:
Color_list=['red','blue','orange','yellow']
if 'green' in Color_list:
    print('color is present')
else:
    print('color is not present')

color is not present


In [46]:
help('keywords')


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



In [59]:
my_num1=float(input('Enter a number'))
my_num2=float(input('Enter an other number'))

Enter a number5
Enter an other number3


In [48]:
my_num1

'19'

In [49]:
print(my_num1)

19


In [70]:
def addfunction(n1,n2):
    return(n1 * n2)




In [61]:
addfunction(my_num1,my_num2)

15.0

In [71]:
addfunction(10,36)

360

In [72]:
str3.split(' ')

['hellow', '1st', 'python', 'session']

In [73]:
pip install numpy

In [74]:
import numpy as np

In [75]:
l=[1,2,3,4]
a=np.array(l)
print(a)

[1 2 3 4]


In [76]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [77]:
type(a)

numpy.ndarray

In [78]:
t=(1,2,3,4)
b=np.array(t)
print(b)

[1 2 3 4]


In [81]:
c=np.array((1,2,3,4),dtype='float')
c

array([1., 2., 3., 4.])

In [83]:
c=np.array((11,22,33,44),dtype='str')
c

array(['11', '22', '33', '44'], dtype='<U2')

In [93]:
c=np.array(['abc','bcde','chtnbg','dfvg'],dtype='str')
c


array(['abc', 'bcde', 'chtnbg', 'dfvg'], dtype='<U6')

In [101]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[8,9,10,11],[12,13,14,16]]])
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 16]]])

In [89]:
arr.dtype

dtype('int32')

In [94]:
c.dtype
print(c.dtype)

<U6


In [97]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('no of dimention :',arr.ndim)

[[[[[1 2 3 4]]]]]
no of dimention : 5


In [102]:
arr.shape

(2, 3)

In [103]:
arr.size

6

In [105]:
a=np.zeros((2,3),dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [106]:
b=np.ones((3,2),dtype=float)
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [108]:
c=np.full((2,3),'abc')
print(c)


[['abc' 'abc' 'abc']
 ['abc' 'abc' 'abc']]


In [110]:
x=np.random.rand()
x

0.37042511725497607

In [112]:
x=np.random.random((2,3))
x

array([[0.62534928, 0.17081684, 0.32254523],
       [0.53520566, 0.56974557, 0.98835707]])

In [114]:
z=np.random.randint(1,10,(2,3))
z

array([[2, 7, 1],
       [7, 6, 9]])

In [124]:
arr=np.arange(1,10,3)

arr

array([1, 4, 7])

In [132]:
f=np.linspace(1,10,4)
f

array([ 1.,  4.,  7., 10.])

In [142]:
d3=np.random.randint(1,20,size=(3,3,2))
d3

array([[[ 7, 11],
        [ 3,  9],
        [13, 18]],

       [[ 6,  3],
        [17,  7],
        [17,  4]],

       [[ 9,  6],
        [15,  4],
        [ 8,  1]]])

In [136]:
size=(3,1,2)
size

(3, 1, 2)

In [144]:
ice_cream={'name':'amrita','weekly intake': 5,'favourite flavour':['coffie','chocolate'] }

In [151]:
for i in ice_cream.values():
       print(i)

amrita
5
['coffie', 'chocolate']


In [154]:
!pip install pandas

In [3]:
import pandas as pd
import numpy as np

In [157]:
print(pd.__version__)

2.0.3


In [158]:
print(np.__version__)

1.24.3


In [184]:

lebels=['a','b','c']
list1=[1,2,25]
arr=np.array([1,2,25])
dic={'a':1,'b':2,'c':25}

In [179]:
pd.Series(data=list1)

0     1
1     2
2    25
dtype: int64

In [180]:
pd.Series(data=list1,index=lebels)

a     1
b     2
c    25
dtype: int64

In [165]:
pd.Series(data=arr)

0     1
1     2
2    25
dtype: int32

In [181]:
pd.Series(list1,lebels)

a     1
b     2
c    25
dtype: int64

In [182]:
pd.Series(arr,lebels)

a     1
b     2
c    25
dtype: int32

In [185]:
pd.Series(dic)

a     1
b     2
c    25
dtype: int64

In [4]:
ser1=pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser1.head()

0    a
1    b
2    c
3    d
4    e
dtype: object